controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: api/

login_check:
    path: /api/login
    methods: [POST]

api_refresh_token:
    path: /api/refresh